### PR TITLE
Take care the null field of entity instance, fix #171.

### LINKED ISSUE #171: Adding new Map/List/Set variable to Java entity throws NPE
I'm new to Gremlin and graph DB. 
Initially I created a Java entity to hold three variables like below

`@Data
@Vertex
@AllArgsConstructor
@NoArgsConstructor
public class Employee {
    @Id
    private String id;

    private String name;

    private Integer age;
}`

Using the above bean few Vertices were saved sucessfully in Gremlin(Azure cosmosDB) .
Added a new property called joiningDate to Java Entity and saved few objects but on querying using findAll throws NPE.

`@Data
@Vertex
@AllArgsConstructor
@NoArgsConstructor
public class Employee {

    @Id
    private String id;

    private String name;

    private Integer age;

    private Map departments;
}
`

## Expected Behavior
NPE shouldn't be thrown and the objects correctly mapped to the corresponding Java Entity/bean

## Current Behavior
Null Pointer in AbstractGremlinSourceReader due to field not present in some of the vertex of GraphDB

## Possible Solution
In AbstractGremlinSourceReader class, in the readProperty method there could be null check in the objectmapper for variable 'value' and if null its correspoding type be assigned to null.

## Steps to Reproduce (for bugs)
Step1: Use the First Employee Java Object and persist an vertex

```java
GremlinTemplate secondaryGremlinTemplate = new GremlinTemplate(secondaryGremlinFactory,mappingGremlinConverter);
Employee employeeInsert = new Employee();
employeeInsert.setId("Emp1");
employeeInsert.setName("Employee1");
employeeInsert.setAge(20);
secondaryGremlinTemplate.insert(employeeInsert);
```

Step2: Query using the following code to query using findAll
```java
Iterable<Employee> employee = secondaryGremlinTemplate.findAll(Employee.class);
System.out.println("Employee->" + employee);
for (Employee emp1 : employee) {
System.out.println("Employee->" + emp1.getId());
}
```

All dandy
Step3: Use the second Employee object and pesist a new vertex
```java
Employee employee2Insert = new Employee();
employee2Insert.setId("SecEmp2");
employee2Insert.setName("SecEmployee2");
employee2Insert.setAge(30);
Map<String,String> map = new HashMap<>();
map.put("key1","val1");
employee2Insert.setDepartments(map);
secondaryGremlinTemplate.insert(employee2Insert);
```

Step4: Use the following code to query using findAll
```java
Iterable<Employee> employee2Itr = secondaryGremlinTemplate.findAll(Employee.class);
System.out.println("Employee->" + employee2Itr);
for (Employee emp2 : employee) {
	System.out.println("Employee->" + emp2.getId());
```
Throws NPE on findAll
## Snapshot Code for Reproduce 
```java
@SpringBootApplication
public class Application {
    public static void main(String... args) {
        SpringApplication.run(Application.class, args);
    }
}
```

## Your Environment
* Version used: 2.0.0
* Operating System and version (desktop or mobile): Microsoft with Azure cosmosDB
* SDK version:

### PR DESCRIPTION
**Pull request by Incarnation-p-lee**
Signed-off-by: Pan Li <panli@microsoft.com>

### CODE REVIEW

File: src/main/java/com/microsoft/spring/data/gremlin/conversion/script/AbstractGremlinScriptLiteral.java [hunk 1]
```diff
@@ -11,6 +11,7 @@
 import com.microsoft.spring.data.gremlin.exception.GremlinUnexpectedEntityTypeException;
 import lombok.NonNull;
 import org.apache.tinkerpop.shaded.jackson.core.JsonProcessingException;
+import org.springframework.lang.Nullable;
```
Comment (xscript) [inline src/main/java/com/microsoft/spring/data/gremlin/conversion/script/AbstractGremlinScriptLiteral.java]: nit: not used?

Comment (Incarnation-p-lee) [reply src/main/java/com/microsoft/spring/data/gremlin/conversion/script/AbstractGremlinScriptLiteral.java]: Yes, will remove this.
